language: node_js
node_js:
- 16.*
sudo: false
services: mongodb
script:
- npm run lint
- npm run doc
- npm test
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
